services:
  next-app:
    build:
      context: .
      dockerfile: Orbit.UI/Dockerfile
    container_name: Orbit-ui
    restart: always
    ports:
      - "3000:3000"
    networks:
      - orbit-network
  orbit-api:
    container_name: orbit-api
    build:
      context: .
      dockerfile: Orbit.Api/Orbit.Api/Dockerfile
    ports:
      - "7000:7000"
    restart: unless-stopped
    networks:
      - orbit-network
networks:
  orbit-network:
    driver: bridge