services:
  next-app:
    build:
      context: .
      dockerfile: Orbit.UI/Dockerfile
    container_name: Orbit-ui
    restart: always
    ports:
      - "3000:3000"
    networks:
      - orbit-network
  orbit-api:
    container_name: orbit-api
    build:
      context: .
      dockerfile: Orbit.Api/Dockerfile
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - orbit-network
  networks:
  npm-network:
    external: true
    name: orbit-network